name: Backend Continuous Deployment

on:
  push:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Oracle JDK
        uses: actions/setup-java@v2
        with:
          java-version: "22"
          distribution: "oracle"
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: backend/mdggu-backend
          push: true
          tags: ${{ github.repository }}:latest
      - name: Deploy Java Application
        run: |
          docker run -d -p 8080:8080 ${{ github.repository }}:latest
