name: Frontend Continuous Deployment

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4 # Docker 이미지 빌드 및 push
        with:
          context: frontend # Dockerfile이 위치한 경로 명시
          file: frontend/Dockerfile
          push: true
          tags: ${{ github.repository }}:frontend-latest
      - name: Deploy Frontend Application
        run: |
          docker run -d -p 3000:3000 ${{ github.repository }}:frontend-latest
